services:
  api:
    build: ./api
    container_name: marrooks-api
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - default
      - proxy

  web:
    build: ./web
    container_name: marrooks-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8086:80"
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
